name: juanmanuel.espinosa
favicon: null
layout_spectrum: 0.9056575461290777
typography_spectrum: 0.1931593674235046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6670786195900291
  lightness: 0.29785467917099595
  saturation: 0.44719614391215146
  rhythmicContrast: 0.9055833267048001
purpose: []
